services:
  movie.redis-cache:
    image: redis:7.4-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - "movie.redis-cache-volume:/var/opt/redis"
    networks:
      - movie-network
  moviedb.api:
    image: moviedb.api
    build:
      context: ./server
      dockerfile: MovieDB.Api/Dockerfile
    depends_on:
      - movie.redis-cache
    networks:
      - movie-network
    ports:
      - 8080:8080
      - 8081:8081
  moviedb.web:
    image: moviedb.web
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - moviedb.api
    networks:
      - movie-network
    ports:
      - 80:80
        
volumes:
  movie.database-volume:
  movie.redis-cache-volume:
  
networks:
  movie-network:
    external: true